### ISSUE TITLE
ImportError: No module named addresslib

### ISSUE THREAD

**Issue by victorjabur** [mailgun/flanker#109]
This import is not working:

from flanker.addresslib import address

Traceback (most recent call last):
  File "/home/jabur/PycharmProjects/scripts/tmp/flanker.py", line 1, in <module>
    from flanker.addresslib import address
  File "/home/jabur/PycharmProjects/scripts/tmp/flanker.py", line 1, in <module>
    from flanker.addresslib import address
ImportError: No module named addresslib

**Comment by gyanCode** [comment]
if your have a file in your current directory called flanker.py the import will look in the current directory instead of the library and will fail..
Rename your file to something else and the error will go away
